---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create deployment
      k8s:
        state: present
        host: https://kubernetes.default.svc.cluster.local
        context: kubernetes-admin@kubernetes
        validate_certs: no
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sample-java
          spec:
            replicas: 4
            selector:
              matchLabels:
                app: sample-java
            template:
              metadata:
                labels:
                  app: sample-java
              spec:
                containers:
                - name: sample-java
                  image: karahansezer/sample-java
                  ports:
                  - containerPort: 9001
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - sample-java
                        topologyKey: kubernetes.io/hostname

    - name: Create service
      k8s:
        state: present
        host: https://kubernetes.default.svc.cluster.local
        context: kubernetes-admin@kubernetes
        validate_certs: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: sample-java-service
          spec:
            selector:
              app: sample-java
            ports:
            - protocol: TCP
              port: 80
              targetPort: 9001

    - name: Create Ingress
      k8s:
        state: present
        host: https://kubernetes.default.svc.cluster.local
        context: kubernetes-admin@kubernetes
        validate_certs: no
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: sample-java-ingress
          spec:
            rules:
            - http:
                paths:
                - path: "/"
                  backend:
                    serviceName: sample-java-service
                    servicePort: 80
